### ISSUE TITLE
Note in README about required files from `keep-only` flag

### ISSUE THREAD

**Issue by bpurinton** [uw-cryo/asp_plot#22]
While running stereo, this flag should be used:

```
--keep-only '.mask .txt .exr .match -L.tif -L_sub.tif -R_sub.tif -D_sub.tif -D.tif -RD.tif -F.tif -PC.tif'
```

Add a clear note in the README and possibly some helpful error messages to remind the user

(cc @ShashankBice, actually that list might be overkill, since I'm not using e.g. the RD, F, PC files in the plots -- but maybe future additions to the plots will make use of these, so leaving them for now in the list)

**Comment by ShashankBice** [comment]
Yeah, some of these files are being preserved right now for exploratory runs if we need to restart at some point with different params. In production runs, the sub files and the .exr files, D file, F file and PC file would be the most important files to preserve.
