### ISSUE TITLE
Resolve swig memory leak warning on OSR object

### ISSUE THREAD

**Issue by bpurinton** [uw-cryo/asp_plot#23]
When tests run, this error occurs:

```
swig/python detected a memory leak of type 'OSRSpatialReferenceShadow *', no destructor found.
```

Get to the bottom of it and resolve the problem.

**Comment by ShashankBice** [comment]
Yeah this is a recurring issue which is associated with pygeotools handling of gdal and circular imports. David has some pointers on it. 
It is most problematic for python files which print output to screen, the output which is passed to other command line scripts during stereo processing. I wrote some downstream bash parsing which clears the output of this swig error and passes the correct variable to the cli script. But we should fix upstream.

Cheers,
Shashank

**Comment by bpurinton** [comment]
Okay, this should be resolved on its own then when I finish the refactoring around Issue #5
