### ISSUE TITLE
Remove requirement for bundle_adjust

### ISSUE THREAD

**Issue by dshean** [uw-cryo/asp_plot#49]
We should allow users to run the core asp_plot for a simple parallel_stereo run, without ba, and potentially without reference DEM.  I think right now those are required as inputs.
Hopefully straightforward to make them optional CLI arguments, and to just skip those sections in the output report if unavailable

**Comment by bpurinton** [comment]
Agreed, this is also related to the WIP I'm doing towards #38. And I'll tackle this aspect soon / in conjunction.
