### ISSUE TITLE
camera_optimization suggestion

### ISSUE THREAD

**Issue by dshean** [uw-cryo/asp_plot#50]
The CLI utility and function names should be clear that this is a plotting tool, not to be confused with a utility that does the actual camera optimization.  Maybe `camera_optimization_plot` or something.
But I think this is only a `csm_linescan_plot` at this point, and only supports linescan input?  At some point, we were hoping to support similar plotting tool for sequence of frame cameras, like the current `orbit_plot.py` tool.  So maybe just csm_plot, or something.  
While we want to plot changes before/after bundle_adjust or jitter_solve, we should also be able to plot a single camera or two cameras, without providing a second "corrected" set.
It would be good to swap in some "clean" test datasets, as the one in the notebook has outliers and is not necessarily representative - this is a minor issue, as I know it is just for testing and development, but these sample figures will inevitably end up used elsewhere, so we should use something that looks good and makes sense, easy to explain, etc.

**Comment by bpurinton** [comment]
- [ ] rename camera_optimization to csm_plot
- [ ] flexible plot for just one camera
- [ ] use clean test data

**Comment by dshean** [comment]
Awesome.  Thanks @bpurinton!
