### ISSUE TITLE
Problem when both input cameras are equal

### ISSUE THREAD

**Issue by oleg-alexandrov** [uw-cryo/asp_plot#54]
The command:

```
  csm_camera_plot \
    --original_cameras file.json \
    --optimized_cameras file.json

```

invoked with the same file specified twice, throws an error. The root cause seems to be that the array of non-zero differences between positions of the two cameras is empty, and then python can't get an index value to estimate bounds. Similar logic exists for orientations.

**Comment by bpurinton** [comment]
Thanks for the note @oleg-alexandrov. Can I ask why you are using the same file twice? Are you just trying to plot one camera, with no optimization?

In that case, there would be nothing to plot since the purpose of the tool is to plot before / after optimization position and angular differences (in your example these would all be 0, hence the error).

If you have a specific use case you are working on (I suppose just plotting the original position and orientation of one camera, not a difference plot?) then I can expand the tool for that use case. Just want to be sure I understand first before implementing anything in code.

**Comment by bpurinton** [comment]
I note that on this commit https://github.com/uw-cryo/asp_plot/commit/fa554c608c6cf5e42ac864205d85400275808fb6 I expanded the tool to optionally plot just one camera before / after optimization. But that still requires a camera before / after optimization e.g.: 

```
$ csm_camera_plot --original_cameras path/to/original_camera_1 \
                      --optimized_cameras path/to/optimized_camera_1 \
                      --map_crs 32728
                      --save_dir path/to/save_directory/
```

and not the same camera twice

**Comment by oleg-alexandrov** [comment]
When the jitter solver is really tightly constraining the camera position,
the position won't move at all, so the plotter will fail as now. The same
will happen if the solver is invoked with 0 iterations, which is a valid
corner case.

**Comment by bpurinton** [comment]
I see, do you have some files you can share so I can debug this issue? Here, by email, by location on pleiades, etc.

**Comment by oleg-alexandrov** [comment]
[test.json](https://github.com/user-attachments/files/17579147/test.json)
I am attaching a little json file that can be passed to both the original and optimized camera option.

**Comment by bpurinton** [comment]
Done. About to merge and bump the version `0.5.2..0.5.3`.

This command:

```
csm_camera_plot --original_cameras tests/test_data/jitter/oleg_test/test.json --optimized_cameras tests/test_data/jitter/oleg_test/test.json
```

Now outputs this figure:

![image](https://github.com/user-attachments/assets/2ad6a99c-6172-4706-b16e-ec6313fa409a)

**Comment by dshean** [comment]
Thanks Oleg for proposing this test case, and Ben for implementing so quickly!
One note - some clobbering of yaxis labels on that output plot, but not the main focus of this issue.  
Also, if we're going to show original values for pitch, roll, yaw, maybe we want to consider an option to similarly plot east, north, altitude components on same axes as the "Original - Optimized" position components?

**Comment by bpurinton** [comment]
> One note - some clobbering of yaxis labels on that output plot, but not the main focus of this issue.

That's the case for the pop-up image that's trying to squeeze onto the screen, but for the actual saved image there isn't overlap.

> Also, if we're going to show original values for pitch, roll, yaw, maybe we want to consider an option to similarly plot east, north, altitude components on same axes as the "Original - Optimized" position components?

Opened an issue: https://github.com/uw-cryo/asp_plot/issues/56
